# Generated by Django 4.2.2 on 2023-06-26 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data_wizard", "0002_auto_20190306_2022"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="run",
            options={"ordering": ("-pk",), "verbose_name": "data wizard run"},
        ),
    ]
