# Generated by Django 3.1.1 on 2021-11-22 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json_data', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CustomWorkflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validated', models.BooleanField(default=False)),
                ('confirmed', models.BooleanField(default=False)),
                ('finalized', models.BooleanField(default=False)),
            ],
        ),
    ]
