# Generated by Django 4.2.2 on 2023-06-27 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sources", "0002_source_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="filesource",
            options={
                "verbose_name": "File for Import",
                "verbose_name_plural": "Import via File",
            },
        ),
        migrations.AlterModelOptions(
            name="urlsource",
            options={
                "verbose_name": "URL for Import",
                "verbose_name_plural": "Import via URL",
            },
        ),
        migrations.AlterField(
            model_name="filesource",
            name="name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Name (Optional)"
            ),
        ),
        migrations.AlterField(
            model_name="urlsource",
            name="name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Name (Optional)"
            ),
        ),
    ]
